a.out:  iter_process_0101.o
	g++ iter_process_0101.o -o a.out

iter_process_0101.o: iter_process_0101.cpp 
	g++ -c  iter_process_0101.cpp -o iter_process_0101.o

clean:
	rm -f iter_process_0101.o  a.out  *.txt *.png
