a.out:  trigonom_mnog_0000.o
	g++ trigonom_mnog_0000.o -o a.out

trigonom_mnog_0000.o: trigonom_mnog_0000.cpp 
	g++ -c  trigonom_mnog_0000.cpp -o trigonom_mnog_0000.o

clean:
	rm -f trigonom_mnog_0000.o  a.out  *.txt *.png
